name: gmail_settimgs_page_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  country_code_picker: ^3.0.0
  country_list_pick: ^1.0.1+6
  country_picker: ^2.0.23
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  get: ^4.6.6
  language_picker: ^0.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
